definitions:
  dto.AddUserReq:
    properties:
      name:
        example: demo_name
        type: string
    type: object
  dto.GetUserResp:
    properties:
      count:
        type: integer
      demos:
        items:
          $ref: '#/definitions/dto.User'
        type: array
    type: object
  dto.JSONResult:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  dto.User:
    properties:
      created_at:
        type: integer
      id:
        type: integer
      string:
        type: string
    type: object
info:
  contact: {}
paths:
  /ddd/api/v1/user:
    post:
      consumes:
      - application/json
      description: add a user to the system so that he will have an identity
      operationId: AddUser
      parameters:
      - description: AddUserReq
        in: body
        name: data
        schema:
          $ref: '#/definitions/dto.AddUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JSONResult'
      summary: add a user to the system
      tags:
      - user
  /ddd/api/v1/users:
    get:
      consumes:
      - application/json
      description: find users from the given condition
      operationId: GetUsers
      parameters:
      - example: 1
        in: query
        name: id
        type: integer
      - example: 10
        in: query
        name: limit
        type: integer
      - example: demo_name
        in: query
        name: name
        type: string
      - example: 0
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/dto.GetUserResp'
              type: object
      summary: find users
      tags:
      - user
swagger: "2.0"
