version: '3'

services:
  mysql:
    image: mysql:1
    container_name: mysql
    build: ./mysql
    volumes:
      - ~/mysql/data:/var/lib/mysql
      - ~/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  my_ddd:
    image: smartlwei/my_ddd
    container_name: my_ddd
    build: ../bdd
    ports:
      - 8080:8080
      - 8081:8081
    # TODO: depends on 没有生效，尝试wait-for-it？
    depends_on:
      - mysql
    volumes:
      - ./conf/ddd_conf.yaml:/app/conf/config.yaml
    command: ["./app"]


# 使用下面的命令启动服务
# docker-compose build --no-cache
# docker-compose up -d