version: '3'

services:
  mysql:
    image: mysql:1
    container_name: mysql
    build: ./mysql
    volumes:
      - ~/mysql/data:/var/lib/mysql
      - ~/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
    container_name: kafka

#  my_ddd:
#    image: my_ddd:1
#    container_name: my_ddd
#    build: ../ddd
#    ports:
#      - 8080:8080
#      - 8081:8081
#    # TODO: depends on 没有生效，尝试wait-for-it？
#    # 先直接restart重试吧
#    # restart: always
#    depends_on:
#      - mysql
#    volumes:
#      - ./conf/ddd_conf.yaml:/app/conf/config.yaml
#    command: [ "./app" ]


# 使用下面的命令启动服务
# docker-compose build --no-cache
# docker-compose up -d