definitions:
  dto.AddDemoReq:
    properties:
      name:
        example: demo_name
        type: string
    type: object
  dto.Demo:
    properties:
      created_at:
        type: integer
      id:
        type: integer
      string:
        type: string
    type: object
  dto.GetDemosResp:
    properties:
      count:
        type: integer
      demos:
        items:
          $ref: '#/definitions/dto.Demo'
        type: array
    type: object
  dto.JSONResult:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /demo/api/v1/demo:
    post:
      consumes:
      - application/json
      description: 数据库增接口demo的描述内容
      operationId: InsertDemo
      parameters:
      - description: AddDemoReq
        in: body
        name: data
        schema:
          $ref: '#/definitions/dto.AddDemoReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JSONResult'
      summary: 数据库增接口demo
      tags:
      - demo
  /demo/api/v1/demos:
    get:
      consumes:
      - application/json
      description: 数据库查接口demo的描述内容
      operationId: GetDemos
      parameters:
      - example: 1
        in: query
        name: id
        type: integer
      - example: 10
        in: query
        name: limit
        type: integer
      - example: demo_name
        in: query
        name: name
        type: string
      - example: 0
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/dto.GetDemosResp'
              type: object
      summary: 数据库查接口demo
      tags:
      - demo
swagger: "2.0"
